// Language resource file for English and Bengali
const translations = {
  en: {
    title: "Mahamaya Enterprise | Hardware, Paint, Electrical, Construction Materials",
    adminTitle: "Admin Dashboard - Mahamaya Enterprise",
    brandTitle: "Mahamaya Enterprise",
    brandTagline: "Hardware · Paint · Electrical",
    navProducts: "Products",
    navContact: "Contact",
    navCall: "Call",
    navWhatsApp: "WhatsApp",
    navQuote: "Quote",
    themeLabel: "Theme",
    themeDark: "Dark mode",
    themeLight: "Light mode",
    heroBadge: "Trusted local supplier — Eraur · Bhatar",
    heroHeadline: "Build with confidence —<br />materials that arrive on time.",
    heroParagraph: "All hardware & building materials — reliable stock, fair rates, quick service. Get updates for today’s rod/cement rate, Berger paint shades, electrical essentials, water line products, and more.",
      menuToggleLabel: "Open menu",
      languageLabel: "Language",
      mapTitle: "Google Map of Eraur, 713121",
    heroWhatsappCta: "Get price on WhatsApp",
    browseProducts: "Browse products",
    copyCall: "Copy call number",
    copySuccess: "Call number copied!",
    heroInfoDelivery: "Delivery support",
    heroInfoStock: "Genuine stock",
    heroInfoHours: "Open daily<br />7:00 AM – 1:00 PM · 4:00 PM – 8:30 PM",
    visitShop: "Visit the shop<br />Vill + PO - Eraur, P.S - Bhatar, District - Purba Bardhaman, PIN - 713121",
    quoteHeading: "Quick quote request",
    topic: "Topic",
    rod: "Rod / TMT",
    cement: "Cement",
    bricks: "Bricks",
    sand: "Sand & Stone",
    paint: "Paint",
    electrical: "Electrical",
    plumbing: "Plumbing / Water Line",
    yourName: "Your name",
    phone: "Phone",
    requirement: "Requirement",
    requirementPlaceholder: "Example: 10 bags cement + 500 bricks delivery to...",
    saveRequest: "Save request",
    sendWhatsapp: "Send on WhatsApp",
    submitReview: "Submit review",
    rating: "Rating",
    question: "Question",
    answer: "Answer",
    feedback: "Your feedback",
    faq: "FAQ",
    products: "Products we supply",
    productsIntro: "Click a product to see details. Prices are shared on call/WhatsApp.",
    featured: "Featured items (tap to add to quote)",
    whyChoose: "Why customers choose us",
    whyPointCommunication: "Clear communication",
    whyPointBulk: "Bulk order support",
    whyPointStock: "Reliable stock",
    customerReviews: "Customer reviews",
    loadingReviews: "Loading reviews...",
    noReviews: "No reviews yet.",
    failedReviews: "Failed to load reviews.",
    contactLocation: "Contact & location",
    contactWhatsappBtn: "WhatsApp",
    contactCallBtn: "Call",
    contactDirectionsBtn: "Directions",
    addressLabel: "Address",
    hoursLabel: "Hours",
    defaultShopAddress: "Vill + PO - Eraur, P.S - Bhatar, District - Purba Bardhaman, PIN - 713121",
    defaultHoursDetail: "Morning: 7:00 AM – 1:00 PM<br />Evening: 4:00 PM – 8:30 PM",
    footerNote: "© 2025 Mahamaya Enterprise. All rights reserved.",
    footerPhoneLabel: "Phone:",
    footerWhatsappLabel: "WhatsApp:",
    footerAddressLabel: "Address:",
    footerHoursLabel: "Hours:",
    defaultShortAddress: "Eraur, 713121",
    footerOpenNote: "Open all days (confirm on festivals)",
    floatingChatTitle: "Chat on WhatsApp",
    floatingCallTitle: "Call now",
    remove: "Remove",
    saveSettings: "Save Settings",
    name: "Name",
    address: "Address",
    whatsapp: "WhatsApp",
    hours: "Hours",
    addFaq: "Add FAQ",
    editFaq: "Edit FAQs & Shop Info",
    quoteDashboard: "Quote Requests Dashboard",
    shopInfoLegend: "Shop Info",
    faqsLegend: "FAQs",
    shopNameLabel: "Name:",
    shopAddressLabel: "Address:",
    shopPhoneLabel: "Phone:",
    shopWhatsappLabel: "WhatsApp:",
    shopHoursLabel: "Hours:",
    shopPhone: "Phone",
    shopWhatsapp: "WhatsApp",
    shopHours: "Hours",
    saving: "Saving...",
    saved: "Saved!",
    failedSave: "Failed to save.",
    loadingQuotes: "Loading...",
    noQuotes: "No quotes found.",
    failedQuotes: "Failed to load quotes.",
    date: "Date",
    invalidPhone: "Please enter a valid phone number.",
    quoteSaveSuccess: "Quote request saved! You can now send it on WhatsApp.",
    quoteSaveFail: "Failed to save quote. Please try again.",
    reviewSubmitFail: "Failed to submit review.",
    messageQuoteFor: "Quote request for",
    messageName: "Name",
    messagePhone: "Phone",
    messageRequirement: "Requirement",
    productTmtName: "Rod / TMT",
    productTmtDesc: "Daily rate updates, wholesale bundles",
    productTmtFeature1: "Multiple grades",
    productTmtFeature2: "Cut-to-length",
    productTmtFeature3: "Fast moving",
    productTmtFeature4: "Bulk supply",
    productCementName: "Cement",
    productCementDesc: "Birla, Dalmia, UltraTech, and more",
    productCementFeature1: "OPC/PPC",
    productCementFeature2: "Construction",
    productCementFeature3: "Site delivery",
    productBricksName: "Bricks",
    productBricksDesc: "First-class, picked and stacked",
    productBricksFeature1: "1st/2nd quality",
    productBricksFeature2: "Site delivery",
    productBricksFeature3: "Bulk",
    productSandName: "Sand & Stone",
    productSandDesc: "Clean river sand, chips",
    productSandFeature1: "Fine/coarse",
    productSandFeature2: "Bulk",
    productSandFeature3: "Delivery options",
    productPaintName: "Paint",
    productPaintDesc: "Berger shades, putty, primer",
    productPaintFeature1: "Berger",
    productPaintFeature2: "Shade suggestions",
    productPaintFeature3: "Genuine products",
    productElectricalName: "Electrical",
    productElectricalDesc: "Cables, switches, lighting",
    productElectricalFeature1: "Branded options",
    productElectricalFeature2: "Safe packaging",
    productElectricalFeature3: "Project-ready",
    productPlumbingName: "Water Line",
    productPlumbingDesc: "Pipes, fittings, tanks",
    productPlumbingFeature1: "Leak-proof fittings",
    productPlumbingFeature2: "Multiple sizes",
    productPlumbingFeature3: "Hardware support",
    // Add more as needed
  },
  bn: {
    title: "মহামায়া এন্টারপ্রাইজ | হার্ডওয়্যার, পেইন্ট, ইলেকট্রিক্যাল, নির্মাণ সামগ্রী",
    adminTitle: "অ্যাডমিন ড্যাশবোর্ড - মহামায়া এন্টারপ্রাইজ",
    brandTitle: "মহামায়া এন্টারপ্রাইজ",
    brandTagline: "হার্ডওয়্যার · পেইন্ট · ইলেকট্রিক্যাল",
    navProducts: "পণ্য",
    navContact: "যোগাযোগ",
    navCall: "কল",
    navWhatsApp: "হোয়াটসঅ্যাপ",
    navQuote: "কোট",
    themeLabel: "থিম",
    themeDark: "ডার্ক মোড",
    themeLight: "লাইট মোড",
    heroBadge: "বিশ্বাসযোগ্য স্থানীয় সরবরাহকারী — এরাউর · ভাতার",
    heroHeadline: "আত্মবিশ্বাসের সাথে নির্মাণ করুন —<br />সময়মতো পৌঁছে যায় এমন উপকরণ।",
      menuToggleLabel: "মেনু খুলুন",
      languageLabel: "ভাষা",
      mapTitle: "এরাউর, ৭১৩১২১ এর গুগল মানচিত্র",
    heroParagraph: "সমস্ত হার্ডওয়্যার ও নির্মাণ সামগ্রী — নির্ভরযোগ্য স্টক, সৎ দাম, দ্রুত পরিষেবা। আজকের রড/সিমেন্ট রেট, বার্জার রং, ইলেকট্রিক্যাল সামগ্রী, ওয়াটার লাইন পণ্যসহ আরও অনেক আপডেট পান।",
    heroWhatsappCta: "হোয়াটসঅ্যাপে দাম নিন",
    browseProducts: "পণ্য দেখুন",
    copyCall: "কল নম্বর কপি করুন",
    copySuccess: "কল নম্বর কপি হয়েছে!",
    heroInfoDelivery: "ডেলিভারি সহায়তা",
    heroInfoStock: "আসল স্টক",
    heroInfoHours: "প্রতিদিন খোলা<br />সকাল ৭:০০ – ১:০০ · সন্ধ্যা ৪:০০ – ৮:৩০",
    visitShop: "দোকানে আসুন<br />গ্রাম + ডাকঘর - এরাউর, পি.এস - ভাতার, জেলা - পূর্ব বর্ধমান, পিন - ৭১৩১২১",
    quoteHeading: "দ্রুত কোট অনুরোধ",
    topic: "বিষয়",
    rod: "রড / টি.এম.টি.",
    cement: "সিমেন্ট",
    bricks: "ইট",
    sand: "বালি ও পাথর",
    paint: "রং",
    electrical: "ইলেকট্রিক্যাল",
    plumbing: "প্লাম্বিং / ওয়াটার লাইন",
    yourName: "আপনার নাম",
    phone: "ফোন",
    requirement: "প্রয়োজনীয়তা",
    requirementPlaceholder: "উদাহরণ: ১০ ব্যাগ সিমেন্ট + ৫০০ ইট ডেলিভারি ...",
    saveRequest: "অনুরোধ সংরক্ষণ করুন",
    sendWhatsapp: "হোয়াটসঅ্যাপে পাঠান",
    submitReview: "রিভিউ জমা দিন",
    rating: "রেটিং",
    question: "প্রশ্ন",
    answer: "উত্তর",
    feedback: "আপনার মতামত",
    faq: "প্রশ্নোত্তর",
    products: "আমরা যে পণ্য সরবরাহ করি",
    productsIntro: "একটি পণ্যে ক্লিক করে বিস্তারিত দেখুন। দাম ফোন বা হোয়াটসঅ্যাপে জানানো হয়।",
    featured: "বিশেষ আইটেম (কোটে যোগ করতে ট্যাপ করুন)",
    whyChoose: "কেন গ্রাহকেরা আমাদের বেছে নেন",
    whyPointCommunication: "পরিষ্কার যোগাযোগ",
    whyPointBulk: "বাল্ক অর্ডার সহায়তা",
    whyPointStock: "বিশ্বস্ত স্টক",
    customerReviews: "গ্রাহক মতামত",
    loadingReviews: "রিভিউ লোড হচ্ছে...",
    noReviews: "কোনো রিভিউ নেই।",
    failedReviews: "রিভিউ লোড করা যায়নি।",
    contactLocation: "যোগাযোগ ও অবস্থান",
    contactWhatsappBtn: "হোয়াটসঅ্যাপ",
    contactCallBtn: "কল",
    contactDirectionsBtn: "দিকনির্দেশ",
    addressLabel: "ঠিকানা",
    hoursLabel: "সময়সূচি",
    defaultShopAddress: "গ্রাম + ডাকঘর - এরাউর, পি.এস - ভাতার, জেলা - পূর্ব বর্ধমান, পিন - ৭১৩১২১",
    defaultHoursDetail: "সকাল: ৭:০০ – ১:০০<br />সন্ধ্যা: ৪:০০ – ৮:৩০",
    footerNote: "© ২০২৫ মহামায়া এন্টারপ্রাইজ। সর্বস্বত্ব সংরক্ষিত।",
    footerPhoneLabel: "ফোন:",
    footerWhatsappLabel: "হোয়াটসঅ্যাপ:",
    footerAddressLabel: "ঠিকানা:",
    footerHoursLabel: "সময়সূচি:",
    defaultShortAddress: "এরাউর, ৭১৩১২১",
    footerOpenNote: "প্রতিদিন খোলা (উৎসবে নিশ্চিত করুন)",
    floatingChatTitle: "হোয়াটসঅ্যাপে চ্যাট করুন",
    floatingCallTitle: "এখনই কল করুন",
    remove: "সরান",
    saveSettings: "সেটিংস সংরক্ষণ করুন",
    name: "নাম",
    address: "ঠিকানা",
    whatsapp: "হোয়াটসঅ্যাপ",
    hours: "ঘন্টা",
    addFaq: "প্রশ্ন যোগ করুন",
    editFaq: "প্রশ্ন ও দোকানের তথ্য সম্পাদনা করুন",
    quoteDashboard: "কোট অনুরোধ ড্যাশবোর্ড",
    shopInfoLegend: "দোকানের তথ্য",
    faqsLegend: "প্রশ্নোত্তর",
    shopNameLabel: "নাম:",
    shopAddressLabel: "ঠিকানা:",
    shopPhoneLabel: "ফোন:",
    shopWhatsappLabel: "হোয়াটসঅ্যাপ:",
    shopHoursLabel: "সময়সূচি:",
    shopPhone: "ফোন",
    shopWhatsapp: "হোয়াটসঅ্যাপ",
    shopHours: "ঘন্টা",
    saving: "সংরক্ষণ করা হচ্ছে...",
    saved: "সংরক্ষিত!",
    failedSave: "সংরক্ষণ ব্যর্থ.",
    loadingQuotes: "লোড হচ্ছে...",
    noQuotes: "কোনো কোট পাওয়া যায়নি।",
    failedQuotes: "কোট লোড করা যায়নি।",
    date: "তারিখ",
    invalidPhone: "অনুগ্রহ করে সঠিক ফোন নম্বর লিখুন।",
    quoteSaveSuccess: "কোট অনুরোধ সংরক্ষিত হয়েছে! এখন আপনি হোয়াটসঅ্যাপে পাঠাতে পারেন।",
    quoteSaveFail: "কোট সংরক্ষণ ব্যর্থ। আবার চেষ্টা করুন।",
    reviewSubmitFail: "রিভিউ জমা দিতে ব্যর্থ হয়েছে।",
    messageQuoteFor: "কোট অনুরোধ",
    messageName: "নাম",
    messagePhone: "ফোন",
    messageRequirement: "প্রয়োজনীয়তা",
    productTmtName: "রড / টি.এম.টি.",
    productTmtDesc: "দৈনিক রেট আপডেট, পাইকারি বান্ডেল",
    productTmtFeature1: "বিভিন্ন গ্রেড",
    productTmtFeature2: "কাট-টু-লেন্থ",
    productTmtFeature3: "দ্রুত মুভিং",
    productTmtFeature4: "বাল্ক সরবরাহ",
    productCementName: "সিমেন্ট",
    productCementDesc: "বিরলা, ডালমিয়া, আল্ট্রাটেক এবং আরও",
    productCementFeature1: "ওপিসি/পিপিসি",
    productCementFeature2: "নির্মাণ",
    productCementFeature3: "সাইটে ডেলিভারি",
    productBricksName: "ইট",
    productBricksDesc: "ফার্স্ট-ক্লাস, খুঁটিয়ে বাছাই",
    productBricksFeature1: "১ম/২য় মান",
    productBricksFeature2: "সাইটে ডেলিভারি",
    productBricksFeature3: "বাল্ক",
    productSandName: "বালি ও পাথর",
    productSandDesc: "পরিষ্কার নদীর বালি, চিপস",
    productSandFeature1: "সূক্ষ্ম/মোটা",
    productSandFeature2: "বাল্ক",
    productSandFeature3: "ডেলিভারি অপশন",
    productPaintName: "রং",
    productPaintDesc: "বার্জার শেড, পুটি, প্রাইমার",
    productPaintFeature1: "বার্জার",
    productPaintFeature2: "শেড পরামর্শ",
    productPaintFeature3: "অরিজিনাল পণ্য",
    productElectricalName: "ইলেকট্রিক্যাল",
    productElectricalDesc: "ক্যাবল, সুইচ, লাইট",
    productElectricalFeature1: "ব্র্যান্ডেড অপশন",
    productElectricalFeature2: "সেফ প্যাকেজিং",
    productElectricalFeature3: "প্রজেক্ট প্রস্তুত",
    productPlumbingName: "ওয়াটার লাইন",
    productPlumbingDesc: "পাইপ, ফিটিং, ট্যাংক",
    productPlumbingFeature1: "লিক-প্রুফ ফিটিং",
    productPlumbingFeature2: "বিভিন্ন সাইজ",
    productPlumbingFeature3: "হার্ডওয়্যার সহায়তা",
    // Add more as needed
  }
};

function t(key, lang = 'en') {
  return translations[lang][key] || translations['en'][key] || key;
}

// Export for use in other scripts
if (typeof module !== 'undefined') module.exports = { translations, t };